/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: noe-3d.at (https://sketchfab.com/www.noe-3d.at)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shell-souvenir-554f19b02ccb406786cf1c59c64ea17c
Title: Shell souvenir
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Shell(props) {
  const { nodes, materials } = useGLTF('/shell_souvenir.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[4.23, 0.205, 18.132]} rotation={[-1.646, 0.188, -3.06]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
        >
          <meshPhysicalMaterial color="pink" roughness={0} metalness={0.8} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
        >
          <meshPhysicalMaterial color="pink" roughness={0} metalness={0} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
        >
          <meshPhysicalMaterial color="pink" roughness={0} metalness={0} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
        >
          <meshPhysicalMaterial color="pink" roughness={0} metalness={0} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
        >
          <meshPhysicalMaterial color="pink" roughness={0} metalness={0} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/shell_souvenir.glb')