/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pnbdesign (https://sketchfab.com/pnbdesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-soul-stone-f074ec968d3b4b45a6c410a179af0d06
Title: Black Soul Stone
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Stone(props) {
  const { nodes, materials } = useGLTF('/black_soul_stone.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.075, 0.266, 0.186]} rotation={[-1.262, 0.009, 0.084]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box001__0.geometry}
            material={materials['Scene_-_Root']}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <meshStandardMaterial color="pink" roughness={0} metalness={1} />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/black_soul_stone.glb')
